In [9]:
import cv2
import numpy as np
import os
from PIL import Image                                                                                

os.chdir('/Users/krothaps/Desktop/hackathon/demo')

In [3]:
image = cv2.imread("image.png")
copy = image.copy()
print image

[[[188  25   0]
  [189  25   0]
  [189  25   0]
  ..., 
  [180  23   0]
  [179  23   0]
  [171  21   0]]

 [[201  27   0]
  [202  27   0]
  [202  27   0]
  ..., 
  [193  26   0]
  [192  25   0]
  [183  24   0]]

 [[212  29   0]
  [213  30   0]
  [214  30   0]
  ..., 
  [204  28   0]
  [202  27   0]
  [192  25   0]]

 ..., 
 [[185  24   0]
  [187  24   0]
  [187  24   0]
  ..., 
  [169  21   0]
  [165  20   0]
  [157  19   0]]

 [[161  20   0]
  [163  20   0]
  [163  20   0]
  ..., 
  [145  16   0]
  [142  16   0]
  [135  14   0]]

 [[152  22   2]
  [153  22   1]
  [153  22   1]
  ..., 
  [137  20   5]
  [135  19   5]
  [129  19   7]]]


In [4]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray', gray)
cv2.waitKey(0)
 
edged = cv2.Canny(gray, 10, 250)
cv2.imshow('Edged', edged)
cv2.waitKey(0)
 
kernel = np.ones((5, 5), np.uint8)
 
dilation = cv2.dilate(edged, kernel, iterations=1)
cv2.imshow('Dilation', dilation)
cv2.waitKey(0)
 
closing = cv2.morphologyEx(dilation, cv2.MORPH_CLOSE, kernel)
cv2.imshow('Closing', closing)
cv2.waitKey(0)
 
# (image, cnts, hiers) = cv2.findContours(closing, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
 
# cont = cv2.drawContours(copy, cnts, -1, (0, 0, 0), 1, cv2.LINE_AA)
# cv2.imshow('Contours', cont)
# cv2.waitKey(0)
 
# mask = np.zeros(cont.shape[:2], dtype="uint8") * 255
 
# # Draw the contours on the mask
# cv2.drawContours(mask, cnts, -1, (255, 255, 255), -1)
 
# # remove the contours from the image and show the resulting images
# img = cv2.bitwise_and(cont, cont, mask=mask)
# cv2.imshow("Mask", img)
# cv2.waitKey(0)
 
# for c in cnts:
#     x, y, w, h = cv2.boundingRect(c)
#     if w > 50 and h > 130:
#         new_img = img[y:y + h, x:x + w]
 
#         cv2.imwrite('Cropped.png', new_img)
#         cv2.imshow("Cropped", new_img)
#         cv2.waitKey(0)

119

In [15]:
import cv2
image = cv2.imread("scenary.jpeg")
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY) # grayscale
_,thresh = cv2.threshold(gray,150,255,cv2.THRESH_BINARY_INV) 
#threshold
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(3,3))
dilated = cv2.dilate(thresh,kernel,iterations = 13) # dilate
contours, hierarchy = cv2.findContours(dilated,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE) 
# get contours
# for each contour found, draw a rectangle around it on original 
image
for contour in contours:
 
    # get rectangle bounding contour
 
    [x,y,w,h] = cv2.boundingRect(contour)
    # discard areas that are too large
 
    if h>300 and w>300:
 
        continue
    # discard areas that are too small
 
    if h<40 or w<40:
 
        continue
    # draw rectangle around contour on original image
 
    cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,255),2)
# write original image with added contours to disk  
 
cv2.imwrite("contoured.jpg", image)

True

In [13]:
import numpy as np
import cv2

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

img = cv2.imread('sachin.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


error: /Users/jenkins/miniconda/0/2.7/conda-bld/work/opencv-2.4.11/modules/imgproc/src/color.cpp:3739: error: (-215) scn == 3 || scn == 4 in function cvtColor


In [10]:
# Baseball

img = Image.open('single_shot_detector_example.jpg')
img.show() 


In [12]:
import numpy as np
import argparse
import cv2
 
# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", required=True,
	help="path to input image")
ap.add_argument("-p", "--prototxt", required=True,
	help="path to Caffe 'deploy' prototxt file")
ap.add_argument("-m", "--model", required=True,
	help="path to Caffe pre-trained model")
ap.add_argument("-c", "--confidence", type=float, default=0.2,
	help="minimum probability to filter weak detections")
args = vars(ap.parse_args())


In [ ]:
# initialize the list of class labels MobileNet SSD was trained to
# detect, then generate a set of bounding box colors for each class
CLASSES = ["background", "aeroplane", "bicycle", "bird", "boat",
	"bottle", "bus", "car", "cat", "chair", "cow", "diningtable",
	"dog", "horse", "motorbike", "person", "pottedplant", "sheep",
	"sofa", "train", "tvmonitor"]
COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))

In [ ]:
# load our serialized model from disk
print("[INFO] loading model...")
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])


In [ ]:
# load the input image and construct an input blob for the image
# by resizing to a fixed 300x300 pixels and then normalizing it
# (note: normalization is done via the authors of the MobileNet SSD
# implementation)
image = cv2.imread(args["image"])
(h, w) = image.shape[:2]
blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 0.007843,
	(300, 300), 127.5)

In [ ]:
# pass the blob through the network and obtain the detections and
# predictions
print("[INFO] computing object detections...")
net.setInput(blob)
detections = net.forward()

In [ ]:
# loop over the detections
for i in np.arange(0, detections.shape[2]):
	# extract the confidence (i.e., probability) associated with the
	# prediction
	confidence = detections[0, 0, i, 2]
 
	# filter out weak detections by ensuring the `confidence` is
	# greater than the minimum confidence
	if confidence > args["confidence"]:
		# extract the index of the class label from the `detections`,
		# then compute the (x, y)-coordinates of the bounding box for
		# the object
		idx = int(detections[0, 0, i, 1])
		box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
		(startX, startY, endX, endY) = box.astype("int")
 
		# display the prediction
		label = "{}: {:.2f}%".format(CLASSES[idx], confidence * 100)
		print("[INFO] {}".format(label))
		cv2.rectangle(image, (startX, startY), (endX, endY),
			COLORS[idx], 2)
		y = startY - 15 if startY - 15 > 15 else startY + 15
		cv2.putText(image, label, (startX, y),
			cv2.FONT_HERSHEY_SIMPLEX, 0.5, COLORS[idx], 2)
